/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as savingContractSol from "./SavingContract.sol";
export type { savingContractSol };
export * as factories from "./factories";
export type { MyToken } from "./ERC20.sol/MyToken";
export { MyToken__factory } from "./factories/ERC20.sol/MyToken__factory";
export type { Saving } from "./SavingContract.sol/Saving";
export { Saving__factory } from "./factories/SavingContract.sol/Saving__factory";
